# Generated by Django 4.2.14 on 2024-07-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefBookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('refbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_managment.refbook')),
            ],
            options={
                'unique_together': {('refbook', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RefBookElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=300, unique=True)),
                ('refbook_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_managment.refbookversion')),
            ],
            options={
                'unique_together': {('refbook_version', 'code')},
            },
        ),
    ]
