# Generated by Django 4.2.14 on 2024-07-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refbook',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='refbookelement',
            options={'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочника'},
        ),
        migrations.AlterModelOptions(
            name='refbookversion',
            options={'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версии справочника'},
        ),
        migrations.AlterUniqueTogether(
            name='refbookversion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='refbook',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='refbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='refbook',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='refbookelement',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код элемента'),
        ),
        migrations.AlterField(
            model_name='refbookelement',
            name='refbook_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_managment.refbookversion', verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='refbookelement',
            name='value',
            field=models.CharField(max_length=300, unique=True, verbose_name='Значение элемента'),
        ),
        migrations.AlterField(
            model_name='refbookversion',
            name='refbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_managment.refbook', verbose_name='Наименование справочника'),
        ),
        migrations.AlterField(
            model_name='refbookversion',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала версии'),
        ),
        migrations.AlterField(
            model_name='refbookversion',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Версия'),
        ),
        migrations.AlterUniqueTogether(
            name='refbookversion',
            unique_together={('refbook', 'version', 'start_date')},
        ),
    ]
