# Generated by Django 4.2.14 on 2024-07-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_managment', '0002_alter_refbook_options_alter_refbookelement_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refbookversion',
            unique_together={('refbook', 'start_date'), ('refbook', 'version')},
        ),
    ]
