# Generated by Django 4.2.14 on 2024-07-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_managment', '0003_alter_refbookversion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refbookelement',
            name='value',
            field=models.CharField(max_length=300, verbose_name='Значение элемента'),
        ),
    ]
